FROM ubuntu:16.04
RUN apt-get update && apt-get install -y python python-dev python3.5 python3.5-dev python-pip libssl-dev libpq-dev git build-essential libfontconfig1 libfontconfig1-dev
RUN pip install setuptools pip --upgrade --force-reinstall
